import { useEffect, useState } from "react";
import type { ExperimentSpec, Factor, StudyAsset, StudyRevision, Condition } from "../shared/experiment";
import type { ProviderId } from "../shared/types";
import { researchApi as api } from "./researchApi";
import type { estimate } from "../server/experiment/service";
type Preview = { conditions: Condition[]; summary: ReturnType<typeof estimate> };
const providers: ProviderId[] = ["openai", "anthropic", "google", "xai"];
function blank(): ExperimentSpec {
  return { id: "research-study", version: "1", title: "Untitled study", factors: [], models: [{ id: "model1", provider: "openai", model: "", parameters: { maxTokens: 2048 } }], replicates: 1, userPromptTemplate: "", systemPrompt: "", measures: [], responseMode: "text", seed: 1, attachments: [], stimulusRules: [], concurrency: { global: 2 }, retry: { maxAttempts: 3, baseDelayMs: 1000 }, limits: { timeoutMs: 120000, maxTotalCalls: 1000 } };
}
function Variables({ value, onChange }: { value: Record<string,string>; onChange: (value: Record<string,string>) => void }) {
  const entries = Object.entries(value);
  return <div className="variable-editor">{entries.map(([key, text], i) => <div className="variable-row" key={i}>
    <label>Variable name<input value={key} onChange={e => { if (e.target.value !== key && Object.hasOwn(value,e.target.value)) return; onChange(Object.fromEntries(entries.map((v,j) => j === i ? [e.target.value, text] : v))); }} /></label>
    <label>Exact text<textarea rows={2} value={text} onChange={e => onChange({ ...value, [key]: e.target.value })} /></label>
    <button className="ghost-button" onClick={() => onChange(Object.fromEntries(entries.filter((_,j) => i !== j)))}>Remove</button>
  </div>)}<button className="ghost-button" onClick={() => { let i=1; while (`variable${i}` in value) i++; onChange({ ...value, [`variable${i}`]: "" }); }}>Add variable</button></div>;
}
function Selector({ factors, value, onChange }: { factors: Factor[]; value: Record<string,string>; onChange: (v: Record<string,string>) => void }) {
  return <div className="selector-grid">{factors.map(f => <label key={f.id}>{f.label || f.id}<select value={value[f.id] ?? ""} onChange={e => { const next = { ...value }; if (e.target.value) next[f.id] = e.target.value; else delete next[f.id]; onChange(next); }}><option value="">All levels</option>{f.levels.map(l => <option key={l.id} value={l.id}>{l.label || l.id}</option>)}</select></label>)}</div>;
}
export default function StudyBuilder({ onBatch }: { onBatch: (id: string) => void }) {
  const [spec, setSpec] = useState<ExperimentSpec>(blank);
  const [projects, setProjects] = useState<StudyRevision[]>([]);
  const [history, setHistory] = useState<StudyRevision[]>([]);
  const [saved, setSaved] = useState<StudyRevision>();
  const [step, setStep] = useState("materials");
  const [preview, setPreview] = useState<Preview>();
  const [conditionIndex, setConditionIndex] = useState(0);
  const [mode, setMode] = useState<"demo"|"live">("demo");
  const [approved, setApproved] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [example, setExample] = useState<ExperimentSpec>();
  const [rates, setRates] = useState<Record<string, { input: string; output: string }>>({});
  const dirty = !saved || JSON.stringify(spec) !== JSON.stringify(saved.spec);
  function change(next: ExperimentSpec) { setSpec(next); setPreview(undefined); setApproved(false); }
  async function work(fn: () => Promise<void>) { setBusy(true); setError(""); setMessage(""); try { await fn(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function refresh() { setProjects(await api<StudyRevision[]>("/projects")); }
  useEffect(() => { void refresh().catch(e => setError(e.message)); api<{experiments:ExperimentSpec[]}>("/experiments").then(data => setExample(data.experiments[0])).catch(e => setError(e.message)); }, []);
  async function save() {
    const revision = await api<StudyRevision>(saved ? `/projects/${saved.projectId}/revisions` : "/projects", { spec, baseRevision: saved?.revisionId });
    setSaved(revision); setSpec(revision.spec); setPreview(undefined); setApproved(false); await refresh(); setHistory(await api(`/projects/${revision.projectId}/revisions`)); setMessage("Saved a new immutable revision.");
    return revision;
  }
  async function upload(file: File) {
    const response = await fetch(`/api/assets?name=${encodeURIComponent(file.name)}`, { method:"POST", headers:{"Content-Type":"application/octet-stream"}, body:file });
    const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Upload failed");
    const asset = data as StudyAsset;
    change({ ...spec, attachments:[...(spec.attachments ?? []), { ...asset, role:"reference", reviewedText:asset.extractedText, reviewed:false, when:{} }] });
    setMessage("Uploaded locally as reference material. Review it before saving; it is not sent to models.");
  }
  const patchFactor = (index: number, factor: Factor) => change({ ...spec, factors:spec.factors.map((f,i) => i===index ? factor : f) });
  const condition = preview?.conditions[conditionIndex] ?? preview?.conditions[0];
  const priced = preview?.summary.models.every(m => rates[m.id] && [rates[m.id].input, rates[m.id].output].every(v => v !== "" && Number.isFinite(Number(v)) && Number(v)>=0));
  const cost = preview?.summary.models.reduce((n,m) => n + (m.inputTokens*Number(rates[m.id]?.input || 0) + m.outputTokens*Number(rates[m.id]?.output || 0))/1000000, 0) ?? 0;
  return <>
    <section className="experiment-card">
      <div className="experiment-section-title"><div><h2>Your study workspace</h2><p>Supply the approved wording and design. The pipeline does not choose measures or rewrite your materials.</p></div></div>
      <div className="builder-toolbar"><label>Open saved project<select value={saved?.projectId ?? ""} onChange={e => { const revision = projects.find(p => p.projectId===e.target.value); if (revision) { setSaved(revision); change(revision.spec); void api<StudyRevision[]>(`/projects/${revision.projectId}/revisions`).then(setHistory).catch(e => setError(e.message)); } }}><option value="">New unsaved project</option>{projects.map(p => <option key={p.projectId} value={p.projectId}>{p.spec.title} · {p.createdAt.slice(0,10)}</option>)}</select></label>
        <button className="ghost-button" onClick={() => { setSaved(undefined); setHistory([]); change(blank()); }}>New blank study</button>
        <button className="ghost-button" disabled={!example} onClick={() => { setSaved(undefined); setHistory([]); change({ ...structuredClone(example!), responseMode:"json", limits:{timeoutMs:120000,maxTotalCalls:23040} }); }}>Load document’s Study 2 preset</button>
        <button className="primary-button" disabled={busy || !dirty} onClick={() => void work(async () => { await save(); })}>Save revision</button>
      </div>
      <label>Study title<input value={spec.title} onChange={e => change({...spec,title:e.target.value})} /></label>
      <p className="experiment-muted">{dirty ? "Unsaved changes" : `Saved revision ${saved?.revisionId.slice(0,8)}`} · Original documents and previous revisions are retained. The Study 2 preset uses the document’s six ratings plus reasoning, 48 conditions, and 30 repetitions. Review the example model choices and supplied materials before use.</p>
      {history.length>0 && <details><summary>Revision history & configuration import</summary><div className="builder-toolbar"><select aria-label="Revision history" value={saved?.revisionId ?? ""} onChange={e => { const r=history.find(h=>h.revisionId===e.target.value); if(r) {setSaved(r); change(r.spec);} }}>{history.map(r=><option key={r.revisionId} value={r.revisionId}>{r.createdAt} · {r.revisionId.slice(0,8)}</option>)}</select><button className="ghost-button" onClick={()=>{setSaved(undefined); change({...spec,projectId:undefined,revisionId:undefined});}}>Fork as new project</button></div></details>}
      <details><summary>Import an exported study specification</summary><p className="experiment-muted">Import study-spec.json from an archive. Referenced attachments must already exist in this installation; upload them again and review their mappings on a new installation.</p><input aria-label="Import study specification" type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0]; if(f) void work(async()=>{const imported=JSON.parse(await f.text()); await api("/experiments/preview",{spec:imported,mode:"demo"}); setSaved(undefined); change({...imported,projectId:undefined,revisionId:undefined});}); e.currentTarget.value="";}} /></details>
    </section>
    <nav className="builder-steps" aria-label="Study setup steps">{[["materials","1 · Materials"],["design","2 · Prompts & conditions"],["execution","3 · Models & limits"],["review","4 · Review & create"]].map(([id,label])=><button key={id} className={step===id?"selected":""} onClick={()=>setStep(id)}>{label}</button>)}</nav>
    {error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    {step==="materials" && <section className="experiment-card"><h2>Reference documents & stimuli</h2><p>Files stay on this computer. Reference documents are never automatically inserted into a prompt. Text stimuli use the reviewed text shown below; PNG/JPEG stimuli are sent as images.</p>
      <label className="upload-field">Attach research materials<input type="file" disabled={busy} accept=".docx,.pdf,.txt,.md,.csv,.json,.png,.jpg,.jpeg" onChange={e=>{const file=e.target.files?.[0];if(file) void work(()=>upload(file));e.currentTarget.value="";}} /></label>
      <p className="experiment-muted">DOCX, text PDF, UTF-8 text, PNG and JPEG. Maximum 10 MB per file. Scanned documents need manual transcription; no OCR or automatic interpretation.</p>
      {(spec.attachments??[]).map((asset,index)=>{const update=(patch:Partial<typeof asset>)=>change({...spec,attachments:spec.attachments!.map((a,i)=>i===index?{...a,...patch}:a)});return <article className="builder-subcard" key={asset.id}>
        <div className="builder-toolbar"><h3>{asset.name}</h3><a className="ghost-button" href={`/api/assets/${asset.id}/original`}>Download original</a><button className="ghost-button" onClick={()=>change({...spec,attachments:spec.attachments!.filter((_,i)=>i!==index)})}>Remove from draft</button></div>
        <label>How this file is used<select value={asset.role} onChange={e=>update({role:e.target.value as "reference"|"stimulus",reviewed:false})}><option value="reference">Reference only · never sent</option><option value="stimulus">Stimulus · sent to selected conditions</option></select></label>
        {asset.warnings.map((w,i)=><p className="experiment-muted" key={i}>{w}</p>)}
        {asset.mime.startsWith("image/")?<img className="asset-preview" src={`/api/assets/${asset.id}/original?preview=true`} alt={asset.name} />:<><details><summary>Original extracted text</summary><pre>{asset.extractedText || "No text extracted"}</pre></details><label>Reviewed text<textarea rows={10} value={asset.reviewedText} onChange={e=>update({reviewedText:e.target.value,reviewed:false})} /></label></>}
        {asset.role==="stimulus" && <><p className="experiment-muted">Send to conditions matching these selections. All levels sends it to every condition.</p><Selector factors={spec.factors} value={asset.when} onChange={when=>update({when,reviewed:false})}/></>}
        <label className="check-label"><input type="checkbox" checked={asset.reviewed} onChange={e=>update({reviewed:e.target.checked})}/>I reviewed this material against the original and confirmed its role and mapping.</label>
      </article>;})}
    </section>}
    {step==="design" && <>
      <section className="experiment-card"><h2>Exact prompts</h2><p>Use variables such as <code>{"{{driver_name}}"}</code> only where the design calls for substitutions. Everything else is preserved verbatim. Response validation does not add instructions to these prompts.</p>
        <label>Default system prompt<textarea rows={5} value={spec.systemPrompt??""} onChange={e=>change({...spec,systemPrompt:e.target.value})}/></label>
        <label>User prompt template<textarea rows={12} value={spec.userPromptTemplate} onChange={e=>change({...spec,userPromptTemplate:e.target.value})}/></label>
      </section>
      <section className="experiment-card"><h2>Factors & levels</h2><p>Every combination becomes one condition. Leave factors empty for a single prompt. A level can provide variables or replace the default system prompt.</p>
        {spec.factors.map((factor,i)=><article className="builder-subcard" key={i}>
          <div className="builder-toolbar"><label>Factor ID<input value={factor.id} onChange={e=>patchFactor(i,{...factor,id:e.target.value})}/></label><label>Factor label<input value={factor.label} onChange={e=>patchFactor(i,{...factor,label:e.target.value})}/></label><button className="ghost-button" onClick={()=>change({...spec,factors:spec.factors.filter((_,j)=>j!==i)})}>Remove factor</button></div>
          {factor.levels.map((level,j)=>{const update=(v:typeof level)=>patchFactor(i,{...factor,levels:factor.levels.map((l,k)=>j===k?v:l)});return <details open className="builder-level" key={j}><summary>{level.label || "New level"}</summary><div className="builder-toolbar"><label>Level ID<input value={level.id} onChange={e=>update({...level,id:e.target.value})}/></label><label>Level label<input value={level.label} onChange={e=>update({...level,label:e.target.value})}/></label><button className="ghost-button" onClick={()=>patchFactor(i,{...factor,levels:factor.levels.filter((_,k)=>j!==k)})}>Remove level</button></div><Variables value={level.vars??{}} onChange={vars=>update({...level,vars})}/><label className="check-label"><input type="checkbox" checked={level.systemPrompt!==undefined} onChange={e=>update({...level,systemPrompt:e.target.checked?"":undefined})}/>This level supplies the system prompt</label>{level.systemPrompt!==undefined&&<textarea aria-label={`System prompt for ${level.label}`} rows={4} value={level.systemPrompt} onChange={e=>update({...level,systemPrompt:e.target.value})}/>}</details>;})}
          <button className="ghost-button" onClick={()=>patchFactor(i,{...factor,levels:[...factor.levels,{id:`level${Date.now()}`,label:"New level",vars:{}}]})}>Add level</button>
        </article>)}
        <button className="ghost-button" onClick={()=>change({...spec,factors:[...spec.factors,{id:`factor${spec.factors.length+1}`,label:"New factor",levels:[{id:"level1",label:"First level",vars:{}}]}]})}>Add factor</button>
      </section>
      <section className="experiment-card"><h2>Scenario mappings</h2><p>Use a mapping when wording depends on a combination, such as behavior and escalation. Matching mappings may not assign the same variable twice.</p>
        {(spec.stimulusRules??[]).map((rule,i)=><article className="builder-subcard" key={i}><Selector factors={spec.factors} value={rule.when} onChange={when=>change({...spec,stimulusRules:spec.stimulusRules!.map((r,j)=>i===j?{...r,when}:r)})}/><Variables value={rule.vars} onChange={vars=>change({...spec,stimulusRules:spec.stimulusRules!.map((r,j)=>i===j?{...r,vars}:r)})}/><button className="ghost-button" onClick={()=>change({...spec,stimulusRules:spec.stimulusRules!.filter((_,j)=>i!==j)})}>Remove mapping</button></article>)}
        <button className="ghost-button" onClick={()=>change({...spec,stimulusRules:[...(spec.stimulusRules??[]),{when:{},vars:{}}]})}>Add scenario mapping</button>
      </section>
      <section className="experiment-card"><h2>Response fields & validation</h2><label>Expected response<select value={spec.responseMode??"json"} onChange={e=>change({...spec,responseMode:e.target.value as "json"|"text"})}><option value="text">Raw text · preserve any nonempty answer</option><option value="json">JSON · validate the fields below</option></select></label>
        {(spec.responseMode??"json")==="json"&&<>{spec.measures.map((m,i)=>{const update=(patch:Partial<typeof m>)=>change({...spec,measures:spec.measures.map((v,j)=>i===j?{...v,...patch}:v)});return <div className="builder-subcard measure-grid" key={i}><label>JSON key<input value={m.id} onChange={e=>update({id:e.target.value})}/></label><label>Label<input value={m.label} onChange={e=>update({label:e.target.value})}/></label><label>Type<select value={m.type} onChange={e=>update({type:e.target.value as typeof m.type})}><option value="integer">Integer</option><option value="number">Number</option><option value="text">Text / category</option></select></label>{m.type!=="text"?<><label>Minimum<input type="number" value={m.min??""} onChange={e=>update({min:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>Maximum<input type="number" value={m.max??""} onChange={e=>update({max:e.target.value===""?undefined:Number(e.target.value)})}/></label></>:<label>Allowed categories (one per line, optional)<textarea rows={2} value={m.allowedValues?.join("\n")??""} onChange={e=>update({allowedValues:e.target.value?e.target.value.split("\n"):undefined})}/></label>}<label className="check-label"><input type="checkbox" checked={m.required??false} onChange={e=>update({required:e.target.checked})}/>Required</label><button className="ghost-button" onClick={()=>change({...spec,measures:spec.measures.filter((_,j)=>j!==i)})}>Remove field</button></div>;})}<button className="ghost-button" onClick={()=>change({...spec,measures:[...spec.measures,{id:`field${spec.measures.length+1}`,label:"New field",type:"integer",required:true}]})}>Add response field</button></>}
        <p className="experiment-muted">Include the exact response-format instructions in your user prompt. No fields or rating scales are chosen for you.</p>
      </section>
    </>}
    {step==="execution"&&<section className="experiment-card"><h2>Models & execution controls</h2><p>Connect providers from the Connections page. Choose exact model versions and parameters for this study.</p>
      {spec.models.map((m,i)=>{const update=(patch:Partial<typeof m>)=>change({...spec,models:spec.models.map((v,j)=>i===j?{...v,...patch}:v)});return <div className="builder-subcard" key={i}><div className="selector-grid"><label>Lane ID<input value={m.id} onChange={e=>update({id:e.target.value})}/></label><label>Provider<select value={m.provider} onChange={e=>update({provider:e.target.value as ProviderId})}>{providers.map(p=><option key={p}>{p}</option>)}</select></label><label>Exact model ID<input value={m.model} onChange={e=>update({model:e.target.value})}/></label><label>Maximum output tokens<input type="number" value={m.parameters?.maxTokens??2048} onChange={e=>update({parameters:{...m.parameters,maxTokens:Number(e.target.value)}})}/></label><label>Temperature (optional)<input type="number" min={0} max={2} step="any" value={m.parameters?.temperature??""} onChange={e=>update({parameters:{...m.parameters,temperature:e.target.value===""?undefined:Number(e.target.value)}})}/></label><label>Top-p (optional)<input type="number" min={0} max={1} step="any" value={m.parameters?.topP??""} onChange={e=>update({parameters:{...m.parameters,topP:e.target.value===""?undefined:Number(e.target.value)}})}/></label><label>Reasoning effort<select value={m.parameters?.reasoningEffort??""} onChange={e=>update({parameters:{...m.parameters,reasoningEffort:(e.target.value||undefined) as NonNullable<typeof m.parameters>["reasoningEffort"]}})}><option value="">Provider default</option>{["none","low","medium","high","xhigh","max"].map(v=><option key={v}>{v}</option>)}</select></label><label>Thinking level<select value={m.parameters?.thinkingLevel??""} onChange={e=>update({parameters:{...m.parameters,thinkingLevel:(e.target.value||undefined) as "low"|"medium"|"high"|undefined}})}><option value="">Provider default</option><option>low</option><option>medium</option><option>high</option></select></label></div><button className="ghost-button" onClick={()=>change({...spec,models:spec.models.filter((_,j)=>i!==j)})}>Remove model</button></div>;})}
      <button className="ghost-button" onClick={()=>change({...spec,models:[...spec.models,{id:`model${Date.now()}`,provider:"openai",model:"",parameters:{maxTokens:2048}}]})}>Add model lane</button>
      <div className="selector-grid run-limits"><label>Repetitions per condition<input type="number" min={1} max={1000} value={spec.replicates} onChange={e=>change({...spec,replicates:Number(e.target.value)})}/></label><label>Order seed<input type="number" value={spec.seed??1} onChange={e=>change({...spec,seed:Number(e.target.value)})}/></label><label>Concurrent calls<input type="number" min={1} max={12} value={spec.concurrency?.global??2} onChange={e=>change({...spec,concurrency:{...spec.concurrency,global:Number(e.target.value)}})}/></label><label>Attempts per call<input type="number" min={1} max={5} value={spec.retry?.maxAttempts??3} onChange={e=>change({...spec,retry:{baseDelayMs:1000,...spec.retry,maxAttempts:Number(e.target.value)}})}/></label><label>Request timeout (seconds)<input type="number" min={1} max={600} value={(spec.limits?.timeoutMs??120000)/1000} onChange={e=>change({...spec,limits:{maxTotalCalls:1000,...spec.limits,timeoutMs:Number(e.target.value)*1000}})}/></label><label>Total call-attempt cap, including retries<input type="number" min={1} max={100000} value={spec.limits?.maxTotalCalls??1000} onChange={e=>change({...spec,limits:{timeoutMs:120000,...spec.limits,maxTotalCalls:Number(e.target.value)}})}/></label></div>
      <p className="experiment-muted">The call cap persists across pauses and restarts. It limits request attempts, not dollars. Requests interrupted after sending may still be billed. Per-provider concurrency defaults to two unless specified in an imported configuration.</p>
    </section>}
    {step==="review"&&<section className="experiment-card"><h2>Review exact outgoing requests</h2><div className="builder-toolbar"><label>Batch mode<select value={mode} onChange={e=>{setMode(e.target.value as "demo"|"live");setApproved(false);}}><option value="demo">Demo fixtures · no external calls</option><option value="live">Live provider APIs</option></select></label><button className="primary-button" disabled={busy} onClick={()=>void work(async()=>{setPreview(await api("/experiments/preview",{spec,mode}));setApproved(false);})}>Validate & preview</button></div>
      {preview&&<><div className="experiment-metrics"><div><strong>{preview.conditions.length}</strong><span>conditions</span></div><div><strong>{preview.summary.totalRuns.toLocaleString()}</strong><span>planned calls</span></div><div><strong>{spec.measures.filter(m=>m.type!=="text").length}</strong><span>numeric response fields</span></div><div><strong>{spec.measures.filter(m=>m.type==="text").length}</strong><span>text fields, including reasoning</span></div></div>
        {spec.limits && spec.limits.maxTotalCalls<preview.summary.totalRuns&&<div className="notice warn">The call cap is below the planned count. This batch will stop before all conditions are completed.</div>}
        {preview.summary.models.map(m=><details key={m.id}><summary>{m.id} · {m.calls} calls · {m.imageCalls} include images</summary><pre>{JSON.stringify({requested:m.requestedParameters,effective:m.effectiveParameters},null,2)}</pre><div className="selector-grid"><label>Reviewed input USD / million tokens<input type="number" min={0} step="any" value={rates[m.id]?.input??""} onChange={e=>setRates(r=>({...r,[m.id]:{input:e.target.value,output:r[m.id]?.output??""}}))}/></label><label>Reviewed output USD / million tokens<input type="number" min={0} step="any" value={rates[m.id]?.output??""} onChange={e=>setRates(r=>({...r,[m.id]:{output:e.target.value,input:r[m.id]?.input??""}}))}/></label></div></details>)}
        <p className="experiment-muted">Estimated text cost at output limits: {mode==="demo"?"$0 (demo)":priced?`$${cost.toFixed(2)}`:"enter rates for every model"}. Excludes retries, image token charges, and other provider charges. Not a dollar spending cap.</p>
        <label>Condition<select value={conditionIndex} onChange={e=>setConditionIndex(Number(e.target.value))}>{preview.conditions.map((c,i)=><option key={c.id} value={i}>{c.id||"Single prompt"}</option>)}</select></label>
        {condition&&<><div className="prompt-columns"><div><h3>System prompt</h3><pre>{condition.systemPrompt||"(No system prompt)"}</pre></div><div><h3>User prompt, including text stimuli</h3><pre>{condition.userPrompt}</pre></div></div>{condition.imageIds?.map(id=><img key={id} className="asset-preview" alt={spec.attachments?.find(a=>a.id===id)?.name} src={`/api/assets/${id}/original?preview=true`}/>)}</>}
        <label className="check-label"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I reviewed the prompts, conditions, fields, attachments, and effective parameters. Use this saved revision for the batch.</label>
        <button className="primary-button" disabled={busy||dirty||!approved||(spec.attachments??[]).some(a=>!a.reviewed)} onClick={()=>void work(async()=>{const created=await api<{manifest:{batchId:string}}>("/batches",{spec,mode,reviewed:true});onBatch(created.manifest.batchId);})}>Create {mode} batch from saved revision</button>
        {dirty&&<p className="experiment-muted">Save this revision first, then confirm the review. Batch creation does not start API calls.</p>}
      </>}
    </section>}
  </>;
}
